/* tslint:disable */
/* eslint-disable */
/**
 * reactor-node
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface RegistrationArgs
 */
export interface RegistrationArgs {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof RegistrationArgs
     */
    'args': { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof RegistrationArgs
     */
    'lib_name': string;
}
/**
 * 
 * @export
 * @interface RemoteActorInfo
 */
export interface RemoteActorInfo {
    /**
     * 
     * @type {string}
     * @memberof RemoteActorInfo
     */
    'hostname': string;
    /**
     * 
     * @type {string}
     * @memberof RemoteActorInfo
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof RemoteActorInfo
     */
    'port': number;
}
/**
 * 
 * @export
 * @interface SpawnArgs
 */
export interface SpawnArgs {
    /**
     * 
     * @type {string}
     * @memberof SpawnArgs
     */
    'actor_name': string;
    /**
     * 
     * @type {string}
     * @memberof SpawnArgs
     */
    'lib_name': string;
    /**
     * 
     * @type {string}
     * @memberof SpawnArgs
     */
    'operator_name': string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof SpawnArgs
     */
    'payload': { [key: string]: any; };
}
/**
 * 
 * @export
 * @interface StatusResponse
 */
export interface StatusResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof StatusResponse
     */
    'actors': Array<string>;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof StatusResponse
     */
    'loaded_libs': { [key: string]: Array<string>; };
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {RemoteActorInfo} remoteActorInfo Remote Actor Detail
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        actorAdded: async (remoteActorInfo: RemoteActorInfo, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'remoteActorInfo' is not null or undefined
            assertParamExists('actorAdded', 'remoteActorInfo', remoteActorInfo)
            const localVarPath = `/actor_added`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(remoteActorInfo, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatus: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {RegistrationArgs} registrationArgs Arguments to compile an operator
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerLib: async (registrationArgs: RegistrationArgs, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'registrationArgs' is not null or undefined
            assertParamExists('registerLib', 'registrationArgs', registrationArgs)
            const localVarPath = `/register_lib`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registrationArgs, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {SpawnArgs} spawnArgs Actor arguments as arbitrary JSON
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        startActor: async (spawnArgs: SpawnArgs, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'spawnArgs' is not null or undefined
            assertParamExists('startActor', 'spawnArgs', spawnArgs)
            const localVarPath = `/start_actor`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(spawnArgs, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        stopAllActors: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/stop_all_actors`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {RemoteActorInfo} remoteActorInfo Remote Actor Detail
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async actorAdded(remoteActorInfo: RemoteActorInfo, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.actorAdded(remoteActorInfo, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.actorAdded']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStatus(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StatusResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStatus(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {RegistrationArgs} registrationArgs Arguments to compile an operator
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerLib(registrationArgs: RegistrationArgs, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerLib(registrationArgs, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.registerLib']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {SpawnArgs} spawnArgs Actor arguments as arbitrary JSON
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async startActor(spawnArgs: SpawnArgs, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RemoteActorInfo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.startActor(spawnArgs, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.startActor']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async stopAllActors(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.stopAllActors(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.stopAllActors']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @param {RemoteActorInfo} remoteActorInfo Remote Actor Detail
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        actorAdded(remoteActorInfo: RemoteActorInfo, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.actorAdded(remoteActorInfo, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatus(options?: RawAxiosRequestConfig): AxiosPromise<StatusResponse> {
            return localVarFp.getStatus(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RegistrationArgs} registrationArgs Arguments to compile an operator
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerLib(registrationArgs: RegistrationArgs, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.registerLib(registrationArgs, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SpawnArgs} spawnArgs Actor arguments as arbitrary JSON
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        startActor(spawnArgs: SpawnArgs, options?: RawAxiosRequestConfig): AxiosPromise<RemoteActorInfo> {
            return localVarFp.startActor(spawnArgs, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        stopAllActors(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.stopAllActors(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @param {RemoteActorInfo} remoteActorInfo Remote Actor Detail
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public actorAdded(remoteActorInfo: RemoteActorInfo, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).actorAdded(remoteActorInfo, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getStatus(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getStatus(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RegistrationArgs} registrationArgs Arguments to compile an operator
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public registerLib(registrationArgs: RegistrationArgs, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).registerLib(registrationArgs, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SpawnArgs} spawnArgs Actor arguments as arbitrary JSON
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public startActor(spawnArgs: SpawnArgs, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).startActor(spawnArgs, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public stopAllActors(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).stopAllActors(options).then((request) => request(this.axios, this.basePath));
    }
}



