/* tslint:disable */
/* eslint-disable */
/**
 * reactor-node
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface CancelledBuilds
 */
export interface CancelledBuilds {
    /**
     * The libraries whose builds were cancelled; their compile requests answer 409.
     * @type {Array<string>}
     * @memberof CancelledBuilds
     */
    'cancelled': Array<string>;
}
/**
 * 
 * @export
 * @interface ClearedCache
 */
export interface ClearedCache {
    /**
     * Disk space the build directories took.
     * @type {number}
     * @memberof ClearedCache
     */
    'freed_bytes': number;
    /**
     * The compiled libraries that were unloaded; the next request for one compiles it again.
     * @type {Array<string>}
     * @memberof ClearedCache
     */
    'unloaded': Array<string>;
}
/**
 * 
 * @export
 * @interface CompilationArgs
 */
export interface CompilationArgs {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CompilationArgs
     */
    'args': { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof CompilationArgs
     */
    'lib_name': string;
}
/**
 * 
 * @export
 * @interface DisableMsgDelayRequest
 */
export interface DisableMsgDelayRequest {
    /**
     * 
     * @type {string}
     * @memberof DisableMsgDelayRequest
     */
    'actor_name': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof DisableMsgDelayRequest
     */
    'senders': Array<string>;
}
/**
 * 
 * @export
 * @interface MsgDelayRequest
 */
export interface MsgDelayRequest {
    /**
     * 
     * @type {string}
     * @memberof MsgDelayRequest
     */
    'actor_name': string;
    /**
     * 
     * @type {number}
     * @memberof MsgDelayRequest
     */
    'delay_range_end': number;
    /**
     * 
     * @type {number}
     * @memberof MsgDelayRequest
     */
    'delay_range_start': number;
    /**
     * 
     * @type {Array<string>}
     * @memberof MsgDelayRequest
     */
    'senders': Array<string>;
}
/**
 * 
 * @export
 * @interface MsgDuplicationRequest
 */
export interface MsgDuplicationRequest {
    /**
     * 
     * @type {string}
     * @memberof MsgDuplicationRequest
     */
    'actor_name': string;
    /**
     * 
     * @type {number}
     * @memberof MsgDuplicationRequest
     */
    'factor': number;
    /**
     * 
     * @type {number}
     * @memberof MsgDuplicationRequest
     */
    'probability': number;
}
/**
 * 
 * @export
 * @interface MsgLossRequest
 */
export interface MsgLossRequest {
    /**
     * 
     * @type {string}
     * @memberof MsgLossRequest
     */
    'actor_name': string;
    /**
     * 
     * @type {number}
     * @memberof MsgLossRequest
     */
    'probability': number;
}
/**
 * 
 * @export
 * @interface RemoteActorInfo
 */
export interface RemoteActorInfo {
    /**
     * 
     * @type {string}
     * @memberof RemoteActorInfo
     */
    'hostname': string;
    /**
     * 
     * @type {string}
     * @memberof RemoteActorInfo
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof RemoteActorInfo
     */
    'port': number;
}
/**
 * 
 * @export
 * @interface SpawnArgs
 */
export interface SpawnArgs {
    /**
     * 
     * @type {string}
     * @memberof SpawnArgs
     */
    'actor_name': string;
    /**
     * 
     * @type {string}
     * @memberof SpawnArgs
     */
    'lib_name': string;
    /**
     * 
     * @type {string}
     * @memberof SpawnArgs
     */
    'operator_name': string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof SpawnArgs
     */
    'payload': { [key: string]: any; };
}
/**
 * 
 * @export
 * @interface StatusResponse
 */
export interface StatusResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof StatusResponse
     */
    'actors': Array<string>;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof StatusResponse
     */
    'loaded_libs': { [key: string]: Array<string>; };
}

/**
 * ActorLifecycleApi - axios parameter creator
 * @export
 */
export const ActorLifecycleApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {RemoteActorInfo} remoteActorInfo Remote Actor Detail
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        actorAdded: async (remoteActorInfo: RemoteActorInfo, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'remoteActorInfo' is not null or undefined
            assertParamExists('actorAdded', 'remoteActorInfo', remoteActorInfo)
            const localVarPath = `/actor_added`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(remoteActorInfo, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatus: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {SpawnArgs} spawnArgs Actor arguments as arbitrary JSON
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        startActor: async (spawnArgs: SpawnArgs, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'spawnArgs' is not null or undefined
            assertParamExists('startActor', 'spawnArgs', spawnArgs)
            const localVarPath = `/start_actor`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(spawnArgs, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} actorAddr Address of the actor to stop
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        stopActor: async (actorAddr: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'actorAddr' is not null or undefined
            assertParamExists('stopActor', 'actorAddr', actorAddr)
            const localVarPath = `/stop_actor/{actor_addr}`
                .replace(`{${"actor_addr"}}`, encodeURIComponent(String(actorAddr)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        stopAllActors: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/stop_all_actors`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ActorLifecycleApi - functional programming interface
 * @export
 */
export const ActorLifecycleApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ActorLifecycleApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {RemoteActorInfo} remoteActorInfo Remote Actor Detail
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async actorAdded(remoteActorInfo: RemoteActorInfo, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.actorAdded(remoteActorInfo, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ActorLifecycleApi.actorAdded']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStatus(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StatusResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStatus(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ActorLifecycleApi.getStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {SpawnArgs} spawnArgs Actor arguments as arbitrary JSON
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async startActor(spawnArgs: SpawnArgs, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RemoteActorInfo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.startActor(spawnArgs, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ActorLifecycleApi.startActor']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} actorAddr Address of the actor to stop
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async stopActor(actorAddr: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.stopActor(actorAddr, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ActorLifecycleApi.stopActor']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async stopAllActors(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.stopAllActors(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ActorLifecycleApi.stopAllActors']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ActorLifecycleApi - factory interface
 * @export
 */
export const ActorLifecycleApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ActorLifecycleApiFp(configuration)
    return {
        /**
         * 
         * @param {RemoteActorInfo} remoteActorInfo Remote Actor Detail
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        actorAdded(remoteActorInfo: RemoteActorInfo, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.actorAdded(remoteActorInfo, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatus(options?: RawAxiosRequestConfig): AxiosPromise<StatusResponse> {
            return localVarFp.getStatus(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SpawnArgs} spawnArgs Actor arguments as arbitrary JSON
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        startActor(spawnArgs: SpawnArgs, options?: RawAxiosRequestConfig): AxiosPromise<RemoteActorInfo> {
            return localVarFp.startActor(spawnArgs, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} actorAddr Address of the actor to stop
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        stopActor(actorAddr: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.stopActor(actorAddr, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        stopAllActors(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.stopAllActors(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ActorLifecycleApi - object-oriented interface
 * @export
 * @class ActorLifecycleApi
 * @extends {BaseAPI}
 */
export class ActorLifecycleApi extends BaseAPI {
    /**
     * 
     * @param {RemoteActorInfo} remoteActorInfo Remote Actor Detail
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ActorLifecycleApi
     */
    public actorAdded(remoteActorInfo: RemoteActorInfo, options?: RawAxiosRequestConfig) {
        return ActorLifecycleApiFp(this.configuration).actorAdded(remoteActorInfo, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ActorLifecycleApi
     */
    public getStatus(options?: RawAxiosRequestConfig) {
        return ActorLifecycleApiFp(this.configuration).getStatus(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SpawnArgs} spawnArgs Actor arguments as arbitrary JSON
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ActorLifecycleApi
     */
    public startActor(spawnArgs: SpawnArgs, options?: RawAxiosRequestConfig) {
        return ActorLifecycleApiFp(this.configuration).startActor(spawnArgs, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} actorAddr Address of the actor to stop
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ActorLifecycleApi
     */
    public stopActor(actorAddr: string, options?: RawAxiosRequestConfig) {
        return ActorLifecycleApiFp(this.configuration).stopActor(actorAddr, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ActorLifecycleApi
     */
    public stopAllActors(options?: RawAxiosRequestConfig) {
        return ActorLifecycleApiFp(this.configuration).stopAllActors(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ChaosApi - axios parameter creator
 * @export
 */
export const ChaosApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {MsgDuplicationRequest} msgDuplicationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setDuplication: async (msgDuplicationRequest: MsgDuplicationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'msgDuplicationRequest' is not null or undefined
            assertParamExists('setDuplication', 'msgDuplicationRequest', msgDuplicationRequest)
            const localVarPath = `/set_duplication`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(msgDuplicationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {MsgDelayRequest} msgDelayRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setMsgDelay: async (msgDelayRequest: MsgDelayRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'msgDelayRequest' is not null or undefined
            assertParamExists('setMsgDelay', 'msgDelayRequest', msgDelayRequest)
            const localVarPath = `/set_msg_delay`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(msgDelayRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {MsgLossRequest} msgLossRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setMsgLoss: async (msgLossRequest: MsgLossRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'msgLossRequest' is not null or undefined
            assertParamExists('setMsgLoss', 'msgLossRequest', msgLossRequest)
            const localVarPath = `/set_msg_loss`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(msgLossRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {DisableMsgDelayRequest} disableMsgDelayRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unsetMsgDelay: async (disableMsgDelayRequest: DisableMsgDelayRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'disableMsgDelayRequest' is not null or undefined
            assertParamExists('unsetMsgDelay', 'disableMsgDelayRequest', disableMsgDelayRequest)
            const localVarPath = `/unset_msg_delay`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(disableMsgDelayRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unsetMsgDuplication: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/unset_msg_duplication`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unsetMsgLoss: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/unset_msg_loss`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ChaosApi - functional programming interface
 * @export
 */
export const ChaosApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ChaosApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {MsgDuplicationRequest} msgDuplicationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setDuplication(msgDuplicationRequest: MsgDuplicationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setDuplication(msgDuplicationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ChaosApi.setDuplication']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {MsgDelayRequest} msgDelayRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setMsgDelay(msgDelayRequest: MsgDelayRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setMsgDelay(msgDelayRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ChaosApi.setMsgDelay']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {MsgLossRequest} msgLossRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setMsgLoss(msgLossRequest: MsgLossRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setMsgLoss(msgLossRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ChaosApi.setMsgLoss']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {DisableMsgDelayRequest} disableMsgDelayRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async unsetMsgDelay(disableMsgDelayRequest: DisableMsgDelayRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.unsetMsgDelay(disableMsgDelayRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ChaosApi.unsetMsgDelay']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async unsetMsgDuplication(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.unsetMsgDuplication(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ChaosApi.unsetMsgDuplication']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async unsetMsgLoss(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.unsetMsgLoss(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ChaosApi.unsetMsgLoss']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ChaosApi - factory interface
 * @export
 */
export const ChaosApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ChaosApiFp(configuration)
    return {
        /**
         * 
         * @param {MsgDuplicationRequest} msgDuplicationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setDuplication(msgDuplicationRequest: MsgDuplicationRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.setDuplication(msgDuplicationRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {MsgDelayRequest} msgDelayRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setMsgDelay(msgDelayRequest: MsgDelayRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.setMsgDelay(msgDelayRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {MsgLossRequest} msgLossRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setMsgLoss(msgLossRequest: MsgLossRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.setMsgLoss(msgLossRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {DisableMsgDelayRequest} disableMsgDelayRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unsetMsgDelay(disableMsgDelayRequest: DisableMsgDelayRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.unsetMsgDelay(disableMsgDelayRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unsetMsgDuplication(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.unsetMsgDuplication(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unsetMsgLoss(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.unsetMsgLoss(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ChaosApi - object-oriented interface
 * @export
 * @class ChaosApi
 * @extends {BaseAPI}
 */
export class ChaosApi extends BaseAPI {
    /**
     * 
     * @param {MsgDuplicationRequest} msgDuplicationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChaosApi
     */
    public setDuplication(msgDuplicationRequest: MsgDuplicationRequest, options?: RawAxiosRequestConfig) {
        return ChaosApiFp(this.configuration).setDuplication(msgDuplicationRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {MsgDelayRequest} msgDelayRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChaosApi
     */
    public setMsgDelay(msgDelayRequest: MsgDelayRequest, options?: RawAxiosRequestConfig) {
        return ChaosApiFp(this.configuration).setMsgDelay(msgDelayRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {MsgLossRequest} msgLossRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChaosApi
     */
    public setMsgLoss(msgLossRequest: MsgLossRequest, options?: RawAxiosRequestConfig) {
        return ChaosApiFp(this.configuration).setMsgLoss(msgLossRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {DisableMsgDelayRequest} disableMsgDelayRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChaosApi
     */
    public unsetMsgDelay(disableMsgDelayRequest: DisableMsgDelayRequest, options?: RawAxiosRequestConfig) {
        return ChaosApiFp(this.configuration).unsetMsgDelay(disableMsgDelayRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChaosApi
     */
    public unsetMsgDuplication(options?: RawAxiosRequestConfig) {
        return ChaosApiFp(this.configuration).unsetMsgDuplication(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChaosApi
     */
    public unsetMsgLoss(options?: RawAxiosRequestConfig) {
        return ChaosApiFp(this.configuration).unsetMsgLoss(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * CompileApi - axios parameter creator
 * @export
 */
export const CompileApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CompilationArgs} compilationArgs Arguments to compile an operator
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buildLib: async (compilationArgs: CompilationArgs, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'compilationArgs' is not null or undefined
            assertParamExists('buildLib', 'compilationArgs', compilationArgs)
            const localVarPath = `/builds`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(compilationArgs, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} libName The library being built
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelBuild: async (libName: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'libName' is not null or undefined
            assertParamExists('cancelBuild', 'libName', libName)
            const localVarPath = `/builds/{lib_name}`
                .replace(`{${"lib_name"}}`, encodeURIComponent(String(libName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelBuilds: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/builds`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        clearBuildCache: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/cache`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CompileApi - functional programming interface
 * @export
 */
export const CompileApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CompileApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CompilationArgs} compilationArgs Arguments to compile an operator
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async buildLib(compilationArgs: CompilationArgs, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.buildLib(compilationArgs, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CompileApi.buildLib']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} libName The library being built
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cancelBuild(libName: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CancelledBuilds>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cancelBuild(libName, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CompileApi.cancelBuild']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cancelBuilds(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CancelledBuilds>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cancelBuilds(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CompileApi.cancelBuilds']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async clearBuildCache(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ClearedCache>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.clearBuildCache(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CompileApi.clearBuildCache']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CompileApi - factory interface
 * @export
 */
export const CompileApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CompileApiFp(configuration)
    return {
        /**
         * 
         * @param {CompilationArgs} compilationArgs Arguments to compile an operator
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buildLib(compilationArgs: CompilationArgs, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.buildLib(compilationArgs, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} libName The library being built
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelBuild(libName: string, options?: RawAxiosRequestConfig): AxiosPromise<CancelledBuilds> {
            return localVarFp.cancelBuild(libName, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelBuilds(options?: RawAxiosRequestConfig): AxiosPromise<CancelledBuilds> {
            return localVarFp.cancelBuilds(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        clearBuildCache(options?: RawAxiosRequestConfig): AxiosPromise<ClearedCache> {
            return localVarFp.clearBuildCache(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CompileApi - object-oriented interface
 * @export
 * @class CompileApi
 * @extends {BaseAPI}
 */
export class CompileApi extends BaseAPI {
    /**
     * 
     * @param {CompilationArgs} compilationArgs Arguments to compile an operator
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CompileApi
     */
    public buildLib(compilationArgs: CompilationArgs, options?: RawAxiosRequestConfig) {
        return CompileApiFp(this.configuration).buildLib(compilationArgs, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} libName The library being built
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CompileApi
     */
    public cancelBuild(libName: string, options?: RawAxiosRequestConfig) {
        return CompileApiFp(this.configuration).cancelBuild(libName, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CompileApi
     */
    public cancelBuilds(options?: RawAxiosRequestConfig) {
        return CompileApiFp(this.configuration).cancelBuilds(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CompileApi
     */
    public clearBuildCache(options?: RawAxiosRequestConfig) {
        return CompileApiFp(this.configuration).clearBuildCache(options).then((request) => request(this.axios, this.basePath));
    }
}



