/*
 * reactor-node
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CancelledBuilds {
    /// The libraries whose builds were cancelled; their compile requests answer 409.
    #[serde(rename = "cancelled")]
    pub cancelled: Vec<String>,
}

impl CancelledBuilds {
    pub fn new(cancelled: Vec<String>) -> CancelledBuilds {
        CancelledBuilds {
            cancelled,
        }
    }
}

