/*
 * reactor-node
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ChaosType {
    #[serde(rename = "Crash")]
    Crash,
    #[serde(rename = "MsgLoss")]
    MsgLoss,
    #[serde(rename = "MsgDuplication")]
    MsgDuplication,
}

impl std::fmt::Display for ChaosType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Crash => write!(f, "Crash"),
            Self::MsgLoss => write!(f, "MsgLoss"),
            Self::MsgDuplication => write!(f, "MsgDuplication"),
        }
    }
}

impl Default for ChaosType {
    fn default() -> ChaosType {
        Self::Crash
    }
}
