/*
 * reactor-node
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChaosConfig {
    #[serde(rename = "actor_name")]
    pub actor_name: String,
    #[serde(rename = "factor", skip_serializing_if = "Option::is_none")]
    pub factor: Option<u32>,
    #[serde(rename = "kind")]
    pub kind: models::ChaosType,
    #[serde(rename = "probability", skip_serializing_if = "Option::is_none")]
    pub probability: Option<f32>,
}

impl ChaosConfig {
    pub fn new(actor_name: String, kind: models::ChaosType) -> ChaosConfig {
        ChaosConfig {
            actor_name,
            factor: None,
            kind,
            probability: None,
        }
    }
}
