/*
 * reactor-node
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClearedCache {
    /// Disk space the build directories took.
    #[serde(rename = "freed_bytes")]
    pub freed_bytes: i64,
    /// The compiled libraries that were unloaded; the next request for one compiles it again.
    #[serde(rename = "unloaded")]
    pub unloaded: Vec<String>,
}

impl ClearedCache {
    pub fn new(freed_bytes: i64, unloaded: Vec<String>) -> ClearedCache {
        ClearedCache {
            freed_bytes,
            unloaded,
        }
    }
}

