/*
 * reactor-node
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DisableMsgDelayRequest {
    #[serde(rename = "actor_name")]
    pub actor_name: String,
    #[serde(rename = "senders")]
    pub senders: Vec<String>,
}

impl DisableMsgDelayRequest {
    pub fn new(actor_name: String, senders: Vec<String>) -> DisableMsgDelayRequest {
        DisableMsgDelayRequest {
            actor_name,
            senders,
        }
    }
}
