/*
 * reactor-node
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MsgDelayRequest {
    #[serde(rename = "actor_name")]
    pub actor_name: String,
    #[serde(rename = "delay_range_end")]
    pub delay_range_end: i64,
    #[serde(rename = "delay_range_start")]
    pub delay_range_start: i64,
    #[serde(rename = "senders")]
    pub senders: Vec<String>,
}

impl MsgDelayRequest {
    pub fn new(
        actor_name: String,
        delay_range_end: i64,
        delay_range_start: i64,
        senders: Vec<String>,
    ) -> MsgDelayRequest {
        MsgDelayRequest {
            actor_name,
            delay_range_end,
            delay_range_start,
            senders,
        }
    }
}
