/*
 * reactor-node
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MsgDuplicationRequest {
    #[serde(rename = "actor_name")]
    pub actor_name: String,
    #[serde(rename = "factor")]
    pub factor: i32,
    #[serde(rename = "probability")]
    pub probability: f32,
}

impl MsgDuplicationRequest {
    pub fn new(actor_name: String, factor: i32, probability: f32) -> MsgDuplicationRequest {
        MsgDuplicationRequest {
            actor_name,
            factor,
            probability,
        }
    }
}
