/*
 * reactor-node
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegistrationArgs {
    #[serde(rename = "args")]
    pub args: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "lib_name")]
    pub lib_name: String,
}

impl RegistrationArgs {
    pub fn new(
        args: std::collections::HashMap<String, serde_json::Value>,
        lib_name: String,
    ) -> RegistrationArgs {
        RegistrationArgs { args, lib_name }
    }
}
