/*
 * reactor-node
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoteActorInfo {
    #[serde(rename = "hostname")]
    pub hostname: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "port")]
    pub port: i32,
}

impl RemoteActorInfo {
    pub fn new(hostname: String, name: String, port: i32) -> RemoteActorInfo {
        RemoteActorInfo {
            hostname,
            name,
            port,
        }
    }
}
