/*
 * reactor-node
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpawnArgs {
    #[serde(rename = "actor_name")]
    pub actor_name: String,
    #[serde(rename = "lib_name")]
    pub lib_name: String,
    #[serde(rename = "operator_name")]
    pub operator_name: String,
    #[serde(rename = "payload")]
    pub payload: std::collections::HashMap<String, serde_json::Value>,
}

impl SpawnArgs {
    pub fn new(
        actor_name: String,
        lib_name: String,
        operator_name: String,
        payload: std::collections::HashMap<String, serde_json::Value>,
    ) -> SpawnArgs {
        SpawnArgs {
            actor_name,
            lib_name,
            operator_name,
            payload,
        }
    }
}
