/*
 * reactor-node
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatusResponse {
    #[serde(rename = "actors")]
    pub actors: Vec<String>,
    #[serde(rename = "loaded_libs")]
    pub loaded_libs: std::collections::HashMap<String, Vec<String>>,
}

impl StatusResponse {
    pub fn new(
        actors: Vec<String>,
        loaded_libs: std::collections::HashMap<String, Vec<String>>,
    ) -> StatusResponse {
        StatusResponse {
            actors,
            loaded_libs,
        }
    }
}
